[tox]
envlist =
    py{310,311}-django52-{sqlite,postgres}
    py{312,313,314}-django{52,60,61}-{sqlite,postgres}

[pytest]
# -- recommended but optional:
python_files = tests.py test_*.py *_tests.py

[testenv]
package = wheel
setenv =
    DJANGO_SETTINGS_MODULE=tests.settings
    PIPENV_VERBOSITY=-1
    PYTHONPATH={toxinidir}
    sqlite: DATABASE_URL=sqlite:memory:
passenv =
    postgres: DATABASE_URL
deps =
    pytest-cov
    pytest-django
    dj-database-url
    tomli
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1
    django61: Django>=6.1,<6.2
    postgres: psycopg[binary]
basepython =
    py314: python3.14
    py313: python3.13
    py312: python3.12
    py311: python3.11
    py310: python3.10
commands =
    pytest --cov=django_shared_property -s tests/tests/

[testenv:flake8]
basepython=python3.11
deps =
    flake8
    flake8-deprecated
    flake8-debugger
    flake8-tidy-imports
    flake8-bugbear
    flake8-eradicate
    flake8-commas
commands =
    flake8 --count src/django_shared_property

[testenv:black]
basepython=python3.11
deps = black
commands = black --diff --check src/django_shared_property tests/ --line-length 119

[testenv:isort]
basepython=python3.11
deps=
    isort
commands=
    isort --diff src tests  --src src/
